### ISSUE TITLE
请问你5.4的vue教程还出嘛

### ISSUE THREAD

**Issue by 578575** [lanceWan/laravue#1]
我是看你的教程才学laravel的,是你的教程带我入门的,现在很想学vue+laravel,但是光下源码看不明白,不知道你还出不出这套视频.

**Comment by lanceWan** [comment]
视频会出的，现在这个项目也是我练手的一个项目，我不可能学完不去做一个实例就去出视频吧。自己先不实践出视频的话，感觉对大家不负责任~ @578575
